"use strict";

// All UI texts. You can translate whole UI by modifying these values.
module.exports = {
  ui: {
    newGame: "New Game",
    throwDice: "Throw Dice",
    highScores: "High Scores",
    ones: "Ones",
    twos: "Twos",
    threes: "Threes",
    fours: "Fours",
    fives: "Fives",
    sixes: "Sixes",
    bonus: "Bonus",
    onePair: "1 Pair",
    twoPairs: "2 Pairs",
    threeOfAKind: "3 of a Kind",
    fourOfAKind: "4 of a Kind",
    smallStraight: "Small Straight",
    largeStraight: "Large Straight",
    fullHouse: "Full House",
    chance: "Chance",
    yatzy: "Yatzy",
    combination: "Combination",
    score: "Score",
    total: "Total Score",
    back: "Back to Game",
    round: "Round",
    throwRound: "Throw",
    player1Name: "Player 1 Name",
    player2Name: "Player 2 Name",
    player3Name: "Player 3 Name",
    player4Name: "Player 4 Name",
    player1Type: "Player 1 Type",
    player2Type: "Player 2 Type",
    player3Type: "Player 3 Type",
    player4Type: "Player 4 Type",
    player: "Player",
    numberOfPlayers: "Number Of Players",
    select: "Select",
    totalRounds: 15,
    totalThrows: 3,
    human: "Human",
    ai: "AI",
    ai_real_name: "Esko",
    ai_message_1: "PLEASE WAIT ... Esko starts new round",
    ai_message_2: "PLEASE WAIT ... Esko throws dice",
    ai_message_3: "PLEASE WAIT ... Esko selects which dice to throw again",
    ai_message_4: "PLEASE WAIT ... Esko selects"
  }
};
